# Copyright 2024 github.com/zadlg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@musl-toolchain//musl-toolchain:all_archives.bzl", "get_default_archive_for")
load("@musl-toolchain//musl-toolchain:types.bzl", "Architecture", "Mode", "Platform")
load("@musl-toolchain//musl-toolchain:download_archive.bzl", "download_archive")

download_archive(
    name = "x86_64-linux-native.ar",
    archive = get_default_archive_for(
        arch = Architecture("x86_64"),
        platform = Platform("linux"),
        mode = Mode("native"),
    ),
    sub_targets = [
        "bin/gcc",
        "bin/g++",
        "bin/cpp",
        "bin/ar",
        "bin/ld",
        "bim/strip",
    ]
)
