load("@musl-toolchain//musl-toolchain:all_archives.bzl", "get_default_archive_for")
load("@musl-toolchain//musl-toolchain:types.bzl", "Architecture", "Mode", "Platform")
load("@musl-toolchain//musl-toolchain:download_archive.bzl", "download_archive")

download_archive("x86_64-linux-native.ar", get_default_archive_for(
    arch = Architecture("x86_64"),
    platform = Platform("linux"),
    mode = Mode("native"),
))
