load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("@musl-toolchain//musl-toolchain:define_toolchain.bzl", "define_cxx_toolchain")

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

define_cxx_toolchain(
    name = "cxx",
    archive = "@musl-toolchain//musl-toolchain/default-toolchains:x86_64-linux-nativee",
    visibility = ["PUBLIC"],
)
