# Copyright 2024 github.com/zadlg
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_musl//musl/archive:rules.bzl", "new_archive")
load("@rules_musl//musl:types.bzl", "Architecture", "Mode", "Platform")
load("@rules_musl//musl:define_toolchain.bzl", "define_cxx_toolchain")
load("@rules_musl//musl:all_archives.bzl", "X86_64_LINUX_NATIVE")

new_archive(
    name = "x86_64-linux-native",
    visibility = ["PUBLIC"],
    **X86_64_LINUX_NATIVE
)
